### ISSUE TITLE
Handle merge commits (multiple parents) and by extension, branches

### ISSUE THREAD

**Issue by joglr** [git-visual/git-visual#61]
Solve with breadth or depth first search

**Comment by tjomson** [comment]
Resolved in #66 in commit 2468e72fe54c00aac77a2bd4bf6b692f82fcd9e7

**Comment by hojelse** [comment]
Still not solved.
\+ Interfaces has support
\- But commit history is not traversing both branches of a merge commit

Solve this with depth first search
